# Generated by Django 6.1.2 on 2026-10-07 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='enlace')),
                ('excerpt', models.CharField(help_text='Resumen corto que se muestra en la lista del blog.', max_length=300, verbose_name='extracto')),
                ('content', models.TextField(verbose_name='contenido')),
                ('image', models.ImageField(blank=True, help_text='Imagen de la entrada (opcional). Se guarda en media/posts/.', upload_to='posts/', verbose_name='imagen')),
                ('published', models.BooleanField(default=True, verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicado el')),
            ],
            options={
                'verbose_name': 'entrada',
                'verbose_name_plural': 'entradas',
                'ordering': ['-published_at'],
            },
        ),
    ]
